### ISSUE TITLE
trainning error

### ISSUE THREAD

**Issue by zhu-xiao-di** [lck1201/win_det_heatmaps#10]
in valid
in eval
Param Tag_threshold 12.0
Param detection_threshold 0.2
Traceback (most recent call last):
  File "/mnt/Code/win_det_heatmaps/common_pytorch/net_modules.py", line 152, in evalNet
    rectify = test_config.rectify, winScoreThres = test_config.windowT)
  File "/mnt/Code/win_det_heatmaps/common_pytorch/group/tag_group.py", line 266, in group_corners_on_tags
    grouped = parser.parse(np.float32(dets), np.float32(tags), idx, ratio, rectify)  # shape=(num_of_windows, 4, 4)
  File "/mnt/Code/win_det_heatmaps/common_pytorch/group/tag_group.py", line 242, in parse
    re = self.calc(det, tag, idx)
  File "/mnt/Code/win_det_heatmaps/common_pytorch/group/tag_group.py", line 178, in calc
    val_k = [c_pts[:, 2, np.newaxis] for c_pts in coords_in_patch_with_score_id]
  File "/mnt/Code/win_det_heatmaps/common_pytorch/group/tag_group.py", line 178, in <listcomp>
    val_k = [c_pts[:, 2, np.newaxis] for c_pts in coords_in_patch_with_score_id]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 158, in <module>
    main()
  File "train.py", line 135, in main
    config.train.patch_width, config.train.patch_height, final_output_path)
  File "/mnt/Code/win_det_heatmaps/common_pytorch/net_modules.py", line 155, in evalNet
    assert 0, (n_s, e, os.path.basename(imdb_list[n_s]['image']))
AssertionError: (0, IndexError('too many indices for array: array is 1-dimensional, but 2 were indexed'), 'result_toushi_2282_6_4.jpg')

**Comment by charvi-077** [comment]
Hi @zhu-xiao-di , were you able to resolve this issue ?

**Comment by charvi-077** [comment]
Update : I figured out that this issue is same as related to issue #5 
We need to have enough data to train again ( even in our case we are using both : our data and facade_dataset as provide in repository, to avoid this error ) , otherwise in evaluation it would not be able to detect the corner points for a given image and end up in this error. 

Thanks.
